name: CI

on:
  push:
  repository_dispatch:
    types:
      - network_store_updated
      - case_updated

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Checkout case client
        uses: actions/checkout@v1
        with:
          repository: powsybl/powsybl-case
          ref: refs/heads/master

      - name: Build and install case client with Maven
        run: mvn --batch-mode -Pclient -DskipTests=true --file ../powsybl-case/pom.xml install

      - name: Checkout single line diagram sources
        uses: actions/checkout@v1
        with:
          repository: powsybl/powsybl-single-line-diagram
          ref: refs/heads/master

      - name: Build and install single line diagram with Maven
        run: mvn --batch-mode -DskipTests=true --file ../powsybl-single-line-diagram/pom.xml install

################### TEMPORARY ################################
      - name: Checkout powsybl core sources from branch integration/mergingview
        uses: actions/checkout@v1
        with:
          repository: powsybl/powsybl-core
          ref: refs/heads/integration/mergingview

      - name: Build and install powsybl core with Maven
        run: mvn --batch-mode -DskipTests=true --file ../powsybl-core/pom.xml install

      - name: Checkout network store sources from branch fix_mergingview_loadflow
        uses: actions/checkout@v1
        with:
          repository: powsybl/powsybl-network-store
          ref: refs/heads/fix_mergingview_loadflow

      - name: Build and install network store client with Maven
        run: mvn --batch-mode -Pclient -DskipTests=true --file ../powsybl-network-store/pom.xml install
###############################################################

      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Build with Maven
        run: mvn --batch-mode -P jacoco verify

      - name: Run SonarCloud analysis
        run: >
          mvn --batch-mode -DskipTests sonar:sonar
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=gridsuite
          -Dsonar.projectKey=org.gridsuite:merge-orchestrator-server
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build Docker image
        if: github.ref == 'refs/heads/master'
        run: >
          mvn --batch-mode deploy -DskipTests -Dmaven.install.skip -Dmaven.deploy.skip -Dpowsybl.docker.deploy
          -Djib.httpTimeout=60000
          -Djib.to.image=docker.io/gridsuite/merge-orchestrator-server
          -Djib.to.auth.username=gridsuiteci
          -Djib.to.auth.password=${{ secrets.DOCKERHUB_TOKEN }}

      - name: Broadcast update event
        if: github.ref == 'refs/heads/master'
        uses: gridsuite/broadcast-event@master
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: merge_orchestrator_server_updated
